apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.bot_name}}
  labels:
    app: {{cookiecutter.bot_name}}
spec:
  selector:
    matchLabels:
      app: {{cookiecutter.bot_name}}
  template:
    metadata:
      name: {{cookiecutter.bot_name}}
      labels:
        app: {{cookiecutter.bot_name}}
    spec:
      securityContext:
        runAsUser: 65534 # nobody
      containers:
      - name: {{cookiecutter.bot_name}}
        image: {{cookiecutter.bot_image_url}}
        env:
        - name: MATTERMOST_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{cookiecutter.bot_name}}
              key: mattermost-token
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.bot_name}}
spec:
  type: ClusterIP
  selector:
    app: {{cookiecutter.bot_name}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{cookiecutter.bot_name}}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{cookiecutter.bot_url}}
    http:
      paths:
        - backend:
            serviceName: {{cookiecutter.bot_name}}
            servicePort: 80
  tls:
  - hosts:
      - {{cookiecutter.bot_url}}
    secretName: tls-{{cookiecutter.bot_name}}

